version: '3'

services:
  server:
    image: dynaer/graydr-react:develop
    ports:
      - "3100:3100"
    volumes:
      - .:/home/drgray/graydr
      - graydr-modules:/home/drgray/node_modules
    working_dir: /home/drgray/graydr

volumes:
  graydr-modules:
